import { Tool, Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'image',
    name: 'Image & Media',
    slug: 'image',
    description: 'Compress, convert, resize, and optimize images with zero cloud upload.',
    iconName: 'Image',
    color: 'from-cyan-500 to-blue-600',
    gradient: 'border-cyan-500/20 hover:border-cyan-400/40 text-cyan-400',
    toolCount: 0,
  },
  {
    id: 'pdf',
    name: 'PDF & Documents',
    slug: 'pdf',
    description: 'Merge, split, compress, and extract pages securely in-browser.',
    iconName: 'FileText',
    color: 'from-rose-500 to-red-600',
    gradient: 'border-rose-500/20 hover:border-rose-400/40 text-rose-400',
    toolCount: 0,
  },
  {
    id: 'developer',
    name: 'Developer Utilities',
    slug: 'developer',
    description: 'Format JSON, inspect JWTs, test RegEx, and encode strings instantly.',
    iconName: 'Code2',
    color: 'from-emerald-500 to-teal-600',
    gradient: 'border-emerald-500/20 hover:border-emerald-400/40 text-emerald-400',
    toolCount: 0,
  },
  {
    id: 'security',
    name: 'Security & Crypto',
    slug: 'security',
    description: 'Cryptographic hash generators, passwords, and client-side encryption.',
    iconName: 'ShieldCheck',
    color: 'from-violet-500 to-purple-600',
    gradient: 'border-violet-500/20 hover:border-violet-400/40 text-violet-400',
    toolCount: 0,
  },
  {
    id: 'qr',
    name: 'QR & Barcode',
    slug: 'qr',
    description: 'Generate customizable dynamic QR codes, WiFi cards, and barcodes.',
    iconName: 'QrCode',
    color: 'from-amber-500 to-orange-600',
    gradient: 'border-amber-500/20 hover:border-amber-400/40 text-amber-400',
    toolCount: 1,
  },
  {
    id: 'career',
    name: 'Career & Writing',
    slug: 'career',
    description: 'ATS resume keyword checker, markdown editor, and visiting card generator.',
    iconName: 'Briefcase',
    color: 'from-blue-500 to-indigo-600',
    gradient: 'border-blue-500/20 hover:border-blue-400/40 text-blue-400',
    toolCount: 1,
  },
  {
    id: 'utilities',
    name: 'Core Utilities',
    slug: 'utilities',
    description: 'Timestamp converters, color pickers, unit transformations, and timers.',
    iconName: 'Cpu',
    color: 'from-pink-500 to-rose-600',
    gradient: 'border-pink-500/20 hover:border-pink-400/40 text-pink-400',
    toolCount: 0,
  },
];

// Active Tools Registry - Add tools one by one on user request
export const TOOLS_REGISTRY: Tool[] = [
  {
    id: 'photo-qr-badge-generator',
    name: 'Photo QR Badge Generator',
    slug: 'photo-qr-badge-generator',
    description: 'Create a QR code badge and place it on your photo. Add URLs, social profiles, Wi-Fi, WhatsApp, contact details, email, phone numbers, or text, then preview and download the finished image.',
    longDescription: 'Photo QR Badge Generator allows you to overlay a highly scannable, fully customized QR code badge onto any photo. Support for website links, social media profiles, Wi-Fi configuration cards, WhatsApp direct chats, vCard contacts, email templates, phone calls, and plain text. 100% client-side privacy with zero cloud upload.',
    category: 'QR & Barcode',
    categorySlug: 'qr',
    iconName: 'QrCode',
    tags: ['qr', 'badge', 'photo', 'watermark', 'wifi-qr', 'vcard', 'whatsapp-qr'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'Popular',
    inputFormat: 'JPG, PNG, WebP',
    outputFormat: 'PNG, JPG',
    processingType: 'client-side',
    version: '1.0.0',
    releaseDate: '2026-09-16',
  },
  {
    id: 'visiting-card-generator',
    name: 'Visiting Card Generator',
    slug: 'visiting-card-generator',
    description: 'Design 1-Side and 2-Side professional business visiting cards with custom photo, logo, and live HD export in PNG, JPG, or PDF.',
    longDescription: 'Create high-resolution, print-ready 1-side and 2-side professional visiting cards directly in your browser. Features 8 single-side and 8 double-side corporate templates, interactive photo framing, real-time live preview, zero cloud storage, and instant HD PDF/PNG exports.',
    category: 'Career & Writing',
    categorySlug: 'career',
    iconName: 'CreditCard',
    tags: ['visiting-card', 'business-card', 'card-generator', 'pdf-card', 'vcard', 'corporate-design'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'New',
    inputFormat: 'JPG, PNG, WebP',
    outputFormat: 'PNG, JPG, PDF',
    processingType: 'client-side',
    version: '1.0.0',
    releaseDate: '2026-09-16',
  },
];
