import { Tool, Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'image',
    name: 'Image & Media',
    slug: 'image',
    description: 'Compress, convert, resize, and optimize images with zero cloud upload.',
    iconName: 'Image',
    color: 'from-cyan-500 to-blue-600',
    gradient: 'border-cyan-500/20 hover:border-cyan-400/40 text-cyan-400',
    toolCount: 0,
  },
  {
    id: 'pdf',
    name: 'PDF & Documents',
    slug: 'pdf',
    description: 'Merge, split, compress, and extract pages securely in-browser.',
    iconName: 'FileText',
    color: 'from-rose-500 to-red-600',
    gradient: 'border-rose-500/20 hover:border-rose-400/40 text-rose-400',
    toolCount: 0,
  },
  {
    id: 'developer',
    name: 'Developer Utilities',
    slug: 'developer',
    description: 'Format JSON, inspect JWTs, test RegEx, and encode strings instantly.',
    iconName: 'Code2',
    color: 'from-emerald-500 to-teal-600',
    gradient: 'border-emerald-500/20 hover:border-emerald-400/40 text-emerald-400',
    toolCount: 0,
  },
  {
    id: 'security',
    name: 'Security & Crypto',
    slug: 'security',
    description: 'Cryptographic hash generators, passwords, and client-side encryption.',
    iconName: 'ShieldCheck',
    color: 'from-violet-500 to-purple-600',
    gradient: 'border-violet-500/20 hover:border-violet-400/40 text-violet-400',
    toolCount: 0,
  },
  {
    id: 'qr',
    name: 'QR & Barcode',
    slug: 'qr',
    description: 'Generate customizable dynamic QR codes, WiFi cards, and barcodes.',
    iconName: 'QrCode',
    color: 'from-amber-500 to-orange-600',
    gradient: 'border-amber-500/20 hover:border-amber-400/40 text-amber-400',
    toolCount: 0,
  },
  {
    id: 'career',
    name: 'Career & Writing',
    slug: 'career',
    description: 'ATS resume keyword checker, markdown editor, and text metrics.',
    iconName: 'Briefcase',
    color: 'from-blue-500 to-indigo-600',
    gradient: 'border-blue-500/20 hover:border-blue-400/40 text-blue-400',
    toolCount: 0,
  },
  {
    id: 'utilities',
    name: 'Core Utilities',
    slug: 'utilities',
    description: 'Timestamp converters, color pickers, unit transformations, and timers.',
    iconName: 'Cpu',
    color: 'from-pink-500 to-rose-600',
    gradient: 'border-pink-500/20 hover:border-pink-400/40 text-pink-400',
    toolCount: 0,
  },
];

// Active Tools Registry - Add tools one by one on user request
export const TOOLS_REGISTRY: Tool[] = [];
