import { Tool, Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'image',
    name: 'Image & Media',
    slug: 'image',
    description: 'Compress, convert, resize, and optimize images with zero cloud upload.',
    iconName: 'Image',
    color: 'from-cyan-500 to-blue-600',
    gradient: 'border-cyan-500/20 hover:border-cyan-400/40 text-cyan-400',
    toolCount: 7,
  },
  {
    id: 'pdf',
    name: 'PDF & Documents',
    slug: 'pdf',
    description: 'Merge, split, compress, and extract pages securely in-browser.',
    iconName: 'FileText',
    color: 'from-rose-500 to-red-600',
    gradient: 'border-rose-500/20 hover:border-rose-400/40 text-rose-400',
    toolCount: 7,
  },
  {
    id: 'developer',
    name: 'Developer Utilities',
    slug: 'developer',
    description: 'Format JSON, inspect JWTs, test RegEx, and encode strings instantly.',
    iconName: 'Code2',
    color: 'from-emerald-500 to-teal-600',
    gradient: 'border-emerald-500/20 hover:border-emerald-400/40 text-emerald-400',
    toolCount: 7,
  },
  {
    id: 'security',
    name: 'Security & Crypto',
    slug: 'security',
    description: 'Cryptographic hash generators, passwords, and client-side encryption.',
    iconName: 'ShieldCheck',
    color: 'from-violet-500 to-purple-600',
    gradient: 'border-violet-500/20 hover:border-violet-400/40 text-violet-400',
    toolCount: 4,
  },
  {
    id: 'qr',
    name: 'QR & Barcode',
    slug: 'qr',
    description: 'Generate customizable dynamic QR codes, WiFi cards, and barcodes.',
    iconName: 'QrCode',
    color: 'from-amber-500 to-orange-600',
    gradient: 'border-amber-500/20 hover:border-amber-400/40 text-amber-400',
    toolCount: 4,
  },
  {
    id: 'career',
    name: 'Career & Writing',
    slug: 'career',
    description: 'ATS resume keyword checker, markdown editor, and text metrics.',
    iconName: 'Briefcase',
    color: 'from-blue-500 to-indigo-600',
    gradient: 'border-blue-500/20 hover:border-blue-400/40 text-blue-400',
    toolCount: 4,
  },
  {
    id: 'utilities',
    name: 'Core Utilities',
    slug: 'utilities',
    description: 'Timestamp converters, color pickers, unit transformations, and timers.',
    iconName: 'Cpu',
    color: 'from-pink-500 to-rose-600',
    gradient: 'border-pink-500/20 hover:border-pink-400/40 text-pink-400',
    toolCount: 4,
  },
];

export const TOOLS_REGISTRY: Tool[] = [
  // Image Category
  {
    id: 'img-compressor',
    name: 'Smart Image Compressor',
    slug: 'image-compressor',
    description: 'Shrink PNG, JPG, and WebP images up to 85% with minimal quality loss.',
    longDescription: 'High-speed browser-based image compression utilizing HTML5 Canvas and WebAssembly. Strips metadata, optimizes Huffman coding tables, and keeps 100% of your visual data on your local device.',
    category: 'Image & Media',
    categorySlug: 'image',
    iconName: 'ImageDown',
    tags: ['image', 'compress', 'png', 'jpg', 'webp', 'optimize'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'Popular',
    inputFormat: 'PNG, JPG, WebP, AVIF',
    outputFormat: 'Optimized Image',
    processingType: 'client-side',
    version: '1.4.0',
    releaseDate: '2026-03-10',
  },
  {
    id: 'img-webp-converter',
    name: 'WebP Converter Engine',
    slug: 'webp-converter',
    description: 'Convert old JPEG & PNG files to modern WebP format for fast web delivery.',
    longDescription: 'Direct format translation to next-generation WebP standard. Provides instant lossless and lossy conversion sliders with live compression factor preview.',
    category: 'Image & Media',
    categorySlug: 'image',
    iconName: 'RefreshCw',
    tags: ['webp', 'convert', 'format', 'images', 'jpg', 'png'],
    status: 'ready',
    isFeatured: false,
    isPopular: true,
    inputFormat: 'JPEG, PNG, GIF, BMP',
    outputFormat: 'WebP',
    processingType: 'client-side',
    version: '1.2.0',
  },
  {
    id: 'img-resizer',
    name: 'Precision Image Resizer',
    slug: 'image-resizer',
    description: 'Batch resize images by exact pixel dimensions, percentage, or aspect ratio.',
    longDescription: 'Bi-cubic and Lanczos-3 interpolation engine for crisp resizing. Supports social media aspect ratio presets (Instagram, Twitter, YouTube, LinkedIn).',
    category: 'Image & Media',
    categorySlug: 'image',
    iconName: 'Scaling',
    tags: ['resize', 'dimensions', 'aspect ratio', 'crop', 'scale'],
    status: 'ready',
    isFeatured: false,
    inputFormat: 'Any Image',
    outputFormat: 'Resized Asset',
    processingType: 'client-side',
  },
  {
    id: 'img-bg-remover',
    name: 'AI Background Remover',
    slug: 'background-remover',
    description: 'Remove backgrounds from portrait and product photos with hair-fine precision.',
    longDescription: 'Browser-accelerated neural segmentation model executing client-side with WebGPU. Clean alpha channel cutout with zero server processing latency.',
    category: 'Image & Media',
    categorySlug: 'image',
    iconName: 'Sparkles',
    tags: ['ai', 'background', 'transparent', 'cutout', 'png'],
    status: 'beta',
    isFeatured: true,
    badge: 'AI Powered',
    inputFormat: 'JPG, PNG',
    outputFormat: 'Transparent PNG',
    processingType: 'wasm',
  },
  {
    id: 'img-svg-optimizer',
    name: 'SVG Clean & Optimizer',
    slug: 'svg-optimizer',
    description: 'Minify SVG code, remove useless XML tags, and reduce vector file sizes.',
    longDescription: 'Strips doctypes, editor namespaces (Illustrator, Inkscape, Figma), cleans path precision, and converts inline styling to compact vector attributes.',
    category: 'Image & Media',
    categorySlug: 'image',
    iconName: 'Layers',
    tags: ['svg', 'vector', 'clean', 'minify', 'xml'],
    status: 'ready',
    inputFormat: 'SVG code or file',
    outputFormat: 'Minified SVG',
    processingType: 'client-side',
  },
  {
    id: 'img-exif-stripper',
    name: 'EXIF Metadata Stripper',
    slug: 'exif-stripper',
    description: 'Remove GPS location coordinates, camera serials, and timestamps from photos.',
    longDescription: 'Guarantees digital privacy before publishing photos online. Clears EXIF, IPTC, and XMP headers completely without altering pixel values.',
    category: 'Image & Media',
    categorySlug: 'image',
    iconName: 'ShieldAlert',
    tags: ['privacy', 'exif', 'metadata', 'gps', 'security'],
    status: 'ready',
    isPopular: true,
    inputFormat: 'JPEG, TIFF, RAW',
    outputFormat: 'Clean Image',
    processingType: 'client-side',
  },
  {
    id: 'img-palette-extractor',
    name: 'Color Palette Extractor',
    slug: 'color-palette-extractor',
    description: 'Extract dominant color palettes, HEX codes, and CSS tokens from any image.',
    longDescription: 'K-Means color clustering algorithm running in worker threads. Generates harmonious color ramps, contrast ratios, and exportable Tailwind color tokens.',
    category: 'Image & Media',
    categorySlug: 'image',
    iconName: 'Palette',
    tags: ['color', 'palette', 'hex', 'css', 'design'],
    status: 'ready',
    inputFormat: 'Any Image',
    outputFormat: 'HEX, RGB, HSL',
    processingType: 'client-side',
  },

  // PDF Category
  {
    id: 'pdf-merge',
    name: 'Ultra PDF Merger',
    slug: 'pdf-merger',
    description: 'Combine multiple PDF files into one clean document with reorder support.',
    longDescription: 'Seamlessly bind dozens of individual PDF files. Drag and drop reordering, page preview thumbnails, and lossless binary stream concatenation in WebAssembly.',
    category: 'PDF & Documents',
    categorySlug: 'pdf',
    iconName: 'Combine',
    tags: ['pdf', 'merge', 'combine', 'documents', 'join'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'Popular',
    inputFormat: 'Multiple PDF files',
    outputFormat: 'Merged PDF',
    processingType: 'client-side',
  },
  {
    id: 'pdf-compress',
    name: 'PDF Stream Compressor',
    slug: 'pdf-compressor',
    description: 'Reduce heavy PDF document size while preserving crisp text readability.',
    longDescription: 'Recompresses embedded raster graphics and flattens unused font subsets. Ideal for email attachments and portal submission size limits.',
    category: 'PDF & Documents',
    categorySlug: 'pdf',
    iconName: 'FileArchive',
    tags: ['pdf', 'compress', 'shrink', 'document', 'size'],
    status: 'ready',
    isPopular: true,
    inputFormat: 'Heavy PDF',
    outputFormat: 'Compressed PDF',
    processingType: 'client-side',
  },
  {
    id: 'pdf-to-img',
    name: 'PDF to High-Res Images',
    slug: 'pdf-to-image',
    description: 'Convert PDF pages into high-resolution JPG or PNG format in one click.',
    longDescription: 'Renders vector PDF pages at up to 300 DPI directly to high-fidelity raster graphics. Download individual pages or a unified ZIP archive.',
    category: 'PDF & Documents',
    categorySlug: 'pdf',
    iconName: 'FileImage',
    tags: ['pdf', 'png', 'jpg', 'pages', 'render'],
    status: 'ready',
    inputFormat: 'PDF Document',
    outputFormat: 'PNG / JPG',
    processingType: 'client-side',
  },
  {
    id: 'pdf-split',
    name: 'PDF Page Splitter',
    slug: 'pdf-splitter',
    description: 'Split specific page ranges or extract individual pages into separate files.',
    longDescription: 'Specify custom page ranges (e.g. 1-3, 5, 8-12) or split every single page into individual standalone documents.',
    category: 'PDF & Documents',
    categorySlug: 'pdf',
    iconName: 'Scissors',
    tags: ['pdf', 'split', 'extract', 'pages', 'slice'],
    status: 'ready',
    inputFormat: 'PDF Document',
    outputFormat: 'Split PDFs',
    processingType: 'client-side',
  },
  {
    id: 'pdf-protect',
    name: 'PDF Password Encryptor',
    slug: 'pdf-password-protect',
    description: 'Lock confidential PDF documents with 256-bit AES encryption and password.',
    longDescription: 'Applies military-grade encryption to prevent unauthorized viewing, printing, copying, or modifying of sensitive contract documents.',
    category: 'PDF & Documents',
    categorySlug: 'pdf',
    iconName: 'FileLock2',
    tags: ['pdf', 'password', 'encrypt', 'security', 'protect'],
    status: 'ready',
    inputFormat: 'PDF Document',
    outputFormat: 'Encrypted PDF',
    processingType: 'client-side',
  },
  {
    id: 'pdf-extract-text',
    name: 'PDF Text Extractor',
    slug: 'pdf-text-extractor',
    description: 'Extract raw text, paragraphs, and tables from PDF documents without formatting loss.',
    longDescription: 'Parses binary text streams inside PDF objects. Outputs clean Markdown, plain TXT, or JSON structure for quick clipboard copy.',
    category: 'PDF & Documents',
    categorySlug: 'pdf',
    iconName: 'FileSearch',
    tags: ['pdf', 'text', 'extract', 'ocr', 'content'],
    status: 'ready',
    inputFormat: 'PDF Document',
    outputFormat: 'Plain Text / Markdown',
    processingType: 'client-side',
  },
  {
    id: 'pdf-md-to-pdf',
    name: 'Markdown to Stylized PDF',
    slug: 'markdown-to-pdf',
    description: 'Transform GitHub-flavored Markdown into beautifully typeset PDF documentation.',
    longDescription: 'Combines elegant CSS typography presets with instant print-to-PDF formatting. Includes syntax highlighting for 40+ programming languages.',
    category: 'PDF & Documents',
    categorySlug: 'pdf',
    iconName: 'FileCode2',
    tags: ['markdown', 'pdf', 'docs', 'export', 'print'],
    status: 'ready',
    inputFormat: 'Markdown (.md)',
    outputFormat: 'Typeset PDF',
    processingType: 'client-side',
  },

  // Developer Tools
  {
    id: 'dev-json-formatter',
    name: 'JSON Formatter & Inspector',
    slug: 'json-formatter',
    description: 'Validate, beautify, minify, and inspect JSON trees with schema error highlighting.',
    longDescription: 'High-performance JSON parser supporting files up to 50MB. Features collapsible tree view, path copy, structural search, and JSON-to-TypeScript type generator.',
    category: 'Developer Utilities',
    categorySlug: 'developer',
    iconName: 'FileJson',
    tags: ['json', 'format', 'lint', 'tree', 'validator', 'minify'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'Essential',
    inputFormat: 'Raw JSON String',
    outputFormat: 'Formatted Tree / Minified',
    processingType: 'client-side',
  },
  {
    id: 'dev-base64',
    name: 'Base64 Encoder & Decoder',
    slug: 'base64-converter',
    description: 'Encode and decode UTF-8 text, binary files, and images into Base64 strings.',
    longDescription: 'RFC 4648 compliant Base64 engine with URL-safe mode support. Convert data URIs, base64 strings, and preview decoded image outputs directly.',
    category: 'Developer Utilities',
    categorySlug: 'developer',
    iconName: 'Binary',
    tags: ['base64', 'encode', 'decode', 'binary', 'utf-8'],
    status: 'ready',
    isPopular: true,
    inputFormat: 'Text or File',
    outputFormat: 'Base64 String',
    processingType: 'client-side',
  },
  {
    id: 'dev-regex',
    name: 'Regex Tester & Matcher',
    slug: 'regex-tester',
    description: 'Interactive Regular Expression playground with real-time capture groups.',
    longDescription: 'Test regular expressions in real-time against custom test strings. Breakdown flags (g, i, m, s, u), color-coded match highlights, and common regex cheatsheet.',
    category: 'Developer Utilities',
    categorySlug: 'developer',
    iconName: 'Regex',
    tags: ['regex', 'regexp', 'test', 'matcher', 'groups'],
    status: 'ready',
    inputFormat: 'Pattern + String',
    outputFormat: 'Matches & Group Array',
    processingType: 'client-side',
  },
  {
    id: 'dev-jwt-decoder',
    name: 'JWT Inspector & Token Viewer',
    slug: 'jwt-decoder',
    description: 'Decode JSON Web Tokens, inspect header claims, payload, and expiry dates.',
    longDescription: 'Client-side JWT parser. View expiration countdowns, issued-at timestamps converted to local time, and inspect algorithm claims without exposing tokens.',
    category: 'Developer Utilities',
    categorySlug: 'developer',
    iconName: 'KeyRound',
    tags: ['jwt', 'token', 'auth', 'decode', 'claims'],
    status: 'ready',
    isPopular: true,
    badge: 'Security Safe',
    inputFormat: 'JWT Token string',
    outputFormat: 'Decoded JSON Claims',
    processingType: 'client-side',
  },
  {
    id: 'dev-hash-generator',
    name: 'Cryptographic Hash Generator',
    slug: 'hash-generator',
    description: 'Generate SHA-1, SHA-256, SHA-512, MD5, and HMAC signatures in real-time.',
    longDescription: 'Hardware-accelerated cryptographic hashing using modern Web Cryptography API (`crypto.subtle`). Fast digest calculation with zero external server reliance.',
    category: 'Developer Utilities',
    categorySlug: 'developer',
    iconName: 'Hash',
    tags: ['hash', 'sha256', 'md5', 'sha512', 'crypto'],
    status: 'ready',
    inputFormat: 'Any Text / String',
    outputFormat: 'Hex Digest Output',
    processingType: 'client-side',
  },
  {
    id: 'dev-uuid-generator',
    name: 'UUID & NanoID Generator',
    slug: 'uuid-generator',
    description: 'Generate cryptographically random UUID v4, v7, and custom NanoIDs.',
    longDescription: 'Batch generation of unique identifiers for database primary keys and API tests. Includes options for uppercase, hyphens, and bulk export to CSV/JSON.',
    category: 'Developer Utilities',
    categorySlug: 'developer',
    iconName: 'Fingerprint',
    tags: ['uuid', 'nanoid', 'guid', 'random', 'v4', 'v7'],
    status: 'ready',
    inputFormat: 'Count & Format Option',
    outputFormat: 'ID List',
    processingType: 'client-side',
  },
  {
    id: 'dev-code-minifier',
    name: 'HTML/CSS/JS Minifier',
    slug: 'code-minifier',
    description: 'Compress web code assets to reduce bundle sizes and improve page speed.',
    longDescription: 'Removes whitespaces, comments, unneeded semicolons, and optimizes CSS color codes. Includes instant side-by-side compression percentage counter.',
    category: 'Developer Utilities',
    categorySlug: 'developer',
    iconName: 'FileCode',
    tags: ['minify', 'compress', 'html', 'css', 'javascript'],
    status: 'ready',
    inputFormat: 'Raw Source Code',
    outputFormat: 'Minified String',
    processingType: 'client-side',
  },

  // Security & Crypto
  {
    id: 'sec-password-gen',
    name: 'Fortress Password Generator',
    slug: 'password-generator',
    description: 'Generate unbreakable passwords and passphrases with entropy analysis.',
    longDescription: 'Uses Web Crypto CSPRNG to produce high-entropy strings. Customize length, symbol sets, exclude ambiguous characters, and test resistance to brute-force attacks.',
    category: 'Security & Crypto',
    categorySlug: 'security',
    iconName: 'Lock',
    tags: ['password', 'generator', 'security', 'entropy', 'random'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'Zero-Trace',
    inputFormat: 'Complexity Parameters',
    outputFormat: 'Secure Password',
    processingType: 'client-side',
  },
  {
    id: 'sec-checksum-verifier',
    name: 'File Checksum Verifier',
    slug: 'file-checksum-verifier',
    description: 'Verify downloaded file integrity by comparing SHA-256 / MD5 checksums.',
    longDescription: 'Drop any file to compute its cryptographic hash directly in the browser. Compare against publisher checksums to detect corrupted or tampered downloads.',
    category: 'Security & Crypto',
    categorySlug: 'security',
    iconName: 'CheckCircle2',
    tags: ['checksum', 'sha256', 'integrity', 'verify', 'hash'],
    status: 'ready',
    inputFormat: 'Any Local File',
    outputFormat: 'Hash Verification Match',
    processingType: 'client-side',
  },
  {
    id: 'sec-rsa-keys',
    name: 'RSA Key Pair Generator',
    slug: 'rsa-key-generator',
    description: 'Generate 2048-bit and 4096-bit RSA public/private key pairs in PEM format.',
    longDescription: 'Web Cryptography key generation for SSH, SSL testing, and asymmetric encryption. Keys are generated exclusively in local browser memory.',
    category: 'Security & Crypto',
    categorySlug: 'security',
    iconName: 'Key',
    tags: ['rsa', 'keys', 'pem', 'ssh', 'crypto'],
    status: 'ready',
    inputFormat: 'Bit Length Selection',
    outputFormat: 'Public & Private PEM',
    processingType: 'client-side',
  },
  {
    id: 'sec-text-encrypt',
    name: 'AES-256 Text Encryptor',
    slug: 'aes-text-encryptor',
    description: 'Encrypt secret text messages with AES-GCM 256 using a custom passphrase.',
    longDescription: 'End-to-end symmetric encryption. Generates ciphertexts with PBKDF2 key derivation and random IVs that can only be decrypted with your exact secret password.',
    category: 'Security & Crypto',
    categorySlug: 'security',
    iconName: 'ShieldAlert',
    tags: ['encrypt', 'decrypt', 'aes', 'gcm', 'secrets'],
    status: 'ready',
    inputFormat: 'Text + Passphrase',
    outputFormat: 'Ciphertext Payload',
    processingType: 'client-side',
  },

  // QR & Barcode
  {
    id: 'qr-custom-generator',
    name: 'Pro Dynamic QR Generator',
    slug: 'qr-code-generator',
    description: 'Design beautiful, customized QR codes with logos, colors, and SVG export.',
    longDescription: 'Vector QR engine supporting URL, text, vCard, and SMS payloads. Customize dots styling, corner markers, error correction levels (L, M, Q, H), and gradient fills.',
    category: 'QR & Barcode',
    categorySlug: 'qr',
    iconName: 'QrCode',
    tags: ['qr', 'generator', 'svg', 'barcode', 'design', 'vcard'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'Vector SVG',
    inputFormat: 'Text, URL, Contact',
    outputFormat: 'PNG, SVG, PDF',
    processingType: 'client-side',
  },
  {
    id: 'qr-wifi-card',
    name: 'WiFi Access QR Generator',
    slug: 'wifi-qr-generator',
    description: 'Generate printable QR cards for guests to connect to WiFi without typing.',
    longDescription: 'Produces standard `WIFI:T:WPA;S:MyNetwork;P:MyPassword;;` encoded barcodes. Includes printable card frame styling for homes and cafes.',
    category: 'QR & Barcode',
    categorySlug: 'qr',
    iconName: 'Wifi',
    tags: ['wifi', 'qr', 'connect', 'print', 'network'],
    status: 'ready',
    inputFormat: 'SSID & Password',
    outputFormat: 'WiFi QR Card',
    processingType: 'client-side',
  },
  {
    id: 'qr-barcode-engine',
    name: 'Standard Barcode Generator',
    slug: 'barcode-generator',
    description: 'Create Code-128, EAN-13, UPC-A, and Code-39 barcodes for inventory.',
    longDescription: 'High-density 1D barcode synthesis. Export sharp vector SVG outputs ready for commercial printing and product label stock.',
    category: 'QR & Barcode',
    categorySlug: 'qr',
    iconName: 'Barcode',
    tags: ['barcode', 'code128', 'ean13', 'upc', 'retail'],
    status: 'ready',
    inputFormat: 'Product / SKU code',
    outputFormat: 'SVG / PNG Barcode',
    processingType: 'client-side',
  },
  {
    id: 'qr-reader',
    name: 'Instant QR Code Scanner',
    slug: 'qr-scanner',
    description: 'Scan QR codes from your webcam or uploaded image files securely.',
    longDescription: 'Real-time video frame analysis using BarcodeDetector API with pure JS fallback. Decodes URLs and payloads without transmitting camera feeds externally.',
    category: 'QR & Barcode',
    categorySlug: 'qr',
    iconName: 'ScanLine',
    tags: ['scan', 'qr', 'camera', 'read', 'decode'],
    status: 'ready',
    inputFormat: 'Camera or Image File',
    outputFormat: 'Decoded URL / Text',
    processingType: 'client-side',
  },

  // Career & Writing
  {
    id: 'career-ats-scanner',
    name: 'ATS Resume Keyword Scanner',
    slug: 'ats-resume-scanner',
    description: 'Analyze resume match scores against target job descriptions instantly.',
    longDescription: 'Natural language tokenization of key skills, certifications, and responsibilities. Highlights missing keywords and readability metrics.',
    category: 'Career & Writing',
    categorySlug: 'career',
    iconName: 'FileCheck',
    tags: ['ats', 'resume', 'cv', 'job', 'keywords', 'career'],
    status: 'ready',
    isFeatured: true,
    isPopular: true,
    badge: 'Career Boost',
    inputFormat: 'Resume + Job Posting',
    outputFormat: 'Match % & Missing Terms',
    processingType: 'client-side',
  },
  {
    id: 'career-word-counter',
    name: 'Live Text & Word Metrics',
    slug: 'word-counter',
    description: 'Real-time count of words, characters, reading time, and speaking duration.',
    longDescription: 'Comprehensive typography analytics: paragraph count, sentence structure, Flesch-Kincaid readability scoring, and keyword density matrix.',
    category: 'Career & Writing',
    categorySlug: 'career',
    iconName: 'Type',
    tags: ['words', 'characters', 'metrics', 'reading time', 'text'],
    status: 'ready',
    inputFormat: 'Raw Text',
    outputFormat: 'Stats & Reading Metrics',
    processingType: 'client-side',
  },
  {
    id: 'career-md-editor',
    name: 'Live Markdown Workspace',
    slug: 'markdown-editor',
    description: 'Split-view live Markdown editor with instant preview, tables, and HTML export.',
    longDescription: 'Distraction-free writing environment with auto-save to browser storage, word tracking, and one-click export to HTML, PDF, or raw Markdown.',
    category: 'Career & Writing',
    categorySlug: 'career',
    iconName: 'Edit3',
    tags: ['markdown', 'editor', 'preview', 'writing', 'notes'],
    status: 'ready',
    inputFormat: 'Markdown Text',
    outputFormat: 'HTML / Rendered View',
    processingType: 'client-side',
  },
  {
    id: 'career-rate-calc',
    name: 'Freelance Hourly Rate Engine',
    slug: 'freelance-rate-calculator',
    description: 'Calculate target hourly and project rates factoring taxes, overhead, and profit.',
    longDescription: 'Formula-based financial planner tailored for tech freelancers and creators. Calculates billable hours, software overhead, health insurance, and savings goals.',
    category: 'Career & Writing',
    categorySlug: 'career',
    iconName: 'Calculator',
    tags: ['freelance', 'rate', 'calculator', 'salary', 'finance'],
    status: 'ready',
    inputFormat: 'Income & Expense Goals',
    outputFormat: 'Calculated Hourly / Daily Rate',
    processingType: 'client-side',
  },

  // Core Utilities
  {
    id: 'util-color-converter',
    name: 'Universal Color Matrix',
    slug: 'color-converter',
    description: 'Convert between HEX, RGB, HSL, HSV, CMYK, and CSS color variables.',
    longDescription: 'Comprehensive color space converter with WCAG AA/AAA contrast checker, color harmony suggestions (analogous, complementary), and CSS output.',
    category: 'Core Utilities',
    categorySlug: 'utilities',
    iconName: 'Pipette',
    tags: ['color', 'hex', 'rgb', 'hsl', 'cmyk', 'contrast'],
    status: 'ready',
    isPopular: true,
    inputFormat: 'Any Color String',
    outputFormat: 'All Formats + Contrast',
    processingType: 'client-side',
  },
  {
    id: 'util-epoch-converter',
    name: 'UNIX Timestamp Engine',
    slug: 'timestamp-converter',
    description: 'Convert epoch seconds and milliseconds to human-readable dates and back.',
    longDescription: 'Handles timezone offsets (UTC, GMT, Local), ISO 8601 strings, relative time diffs, and provides code snippets in Python, JavaScript, and Go.',
    category: 'Core Utilities',
    categorySlug: 'utilities',
    iconName: 'Clock',
    tags: ['timestamp', 'epoch', 'time', 'unix', 'date'],
    status: 'ready',
    inputFormat: 'Timestamp or Date',
    outputFormat: 'Formatted Dates & Code',
    processingType: 'client-side',
  },
  {
    id: 'util-unit-converter',
    name: 'Precision Unit Transformer',
    slug: 'unit-converter',
    description: 'Convert digital storage, data transfer rates, length, mass, and energy.',
    longDescription: 'Zero-latency conversion for engineering and computing metrics. Includes bytes to megabytes/gigabytes (binary vs decimal), bandwidth, and metric units.',
    category: 'Core Utilities',
    categorySlug: 'utilities',
    iconName: 'Compass',
    tags: ['unit', 'convert', 'bytes', 'storage', 'measurement'],
    status: 'ready',
    inputFormat: 'Value + Source Unit',
    outputFormat: 'Converted Values',
    processingType: 'client-side',
  },
  {
    id: 'util-pomodoro',
    name: 'Deep Focus Pomodoro Pulse',
    slug: 'pomodoro-timer',
    description: 'Clean, futuristic interval timer for hyper-focused deep work sessions.',
    longDescription: 'Customizable work/break intervals, ambient browser notifications, visual circular progress ring, and task tracking without audio ads or tracking.',
    category: 'Core Utilities',
    categorySlug: 'utilities',
    iconName: 'Timer',
    tags: ['pomodoro', 'timer', 'focus', 'productivity', 'intervals'],
    status: 'ready',
    inputFormat: 'Timer Settings',
    outputFormat: 'Visual Pulse Session',
    processingType: 'client-side',
  },
];
